language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

install:
  - git clone https://github.com/STAMP-project/testrunner.git && cd testrunner && mvn clean install

script:
  - mvn clean install

after_success:
  - mvn clean test jacoco:report coveralls:report