#!/usr/bin/env bash

## Generated
defects4j checkout -p Math -v 73f -w math_73 && cd math_73 && defects4j compile && cd ..
defects4j checkout -p Math -v 73b -w math_73b && cd math_73b && defects4j compile && cd ..
defects4j checkout -p Math -v 41f -w math_41 && cd math_41 && defects4j compile && cd ..
defects4j checkout -p Math -v 41b -w math_41b && cd math_41b && defects4j compile && cd ..
defects4j checkout -p Math -v 42f -w math_42 && cd math_42 && defects4j compile && cd ..
defects4j checkout -p Math -v 42b -w math_42b && cd math_42b && defects4j compile && cd ..
defects4j checkout -p Chart -v 17f -w chart_17 && cd chart_17 && defects4j compile && cd ..
defects4j checkout -p Chart -v 17b -w chart_17b && cd chart_17b && defects4j compile && cd ..
defects4j checkout -p Math -v 57f -w math_57 && cd math_57 && defects4j compile && cd ..
defects4j checkout -p Math -v 57b -w math_57b && cd math_57b && defects4j compile && cd ..
defects4j checkout -p Time -v 16f -w time_16 && cd time_16 && defects4j compile && cd ..
defects4j checkout -p Time -v 16b -w time_16b && cd time_16b && defects4j compile && cd ..
defects4j checkout -p Chart -v 21f -w chart_21 && cd chart_21 && defects4j compile && cd ..
defects4j checkout -p Chart -v 21b -w chart_21b && cd chart_21b && defects4j compile && cd ..
defects4j checkout -p Math -v 33f -w math_33 && cd math_33 && defects4j compile && cd ..
defects4j checkout -p Math -v 33b -w math_33b && cd math_33b && defects4j compile && cd ..
defects4j checkout -p Chart -v 5f -w chart_5 && cd chart_5 && defects4j compile && cd ..
defects4j checkout -p Chart -v 5b -w chart_5b && cd chart_5b && defects4j compile && cd ..
defects4j checkout -p Lang -v 53f -w lang_53 && cd lang_53 && defects4j compile && cd ..
defects4j checkout -p Lang -v 53b -w lang_53b && cd lang_53b && defects4j compile && cd ..
defects4j checkout -p Lang -v 55f -w lang_55 && cd lang_55 && defects4j compile && cd ..
defects4j checkout -p Lang -v 55b -w lang_55b && cd lang_55b && defects4j compile && cd ..
defects4j checkout -p Math -v 80f -w math_80 && cd math_80 && defects4j compile && cd ..
defects4j checkout -p Math -v 80b -w math_80b && cd math_80b && defects4j compile && cd ..
defects4j checkout -p Time -v 14f -w time_14 && cd time_14 && defects4j compile && cd ..
defects4j checkout -p Time -v 14b -w time_14b && cd time_14b && defects4j compile && cd ..
defects4j checkout -p Chart -v 15f -w chart_15 && cd chart_15 && defects4j compile && cd ..
defects4j checkout -p Chart -v 15b -w chart_15b && cd chart_15b && defects4j compile && cd ..
defects4j checkout -p Math -v 81f -w math_81 && cd math_81 && defects4j compile && cd ..
defects4j checkout -p Math -v 81b -w math_81b && cd math_81b && defects4j compile && cd ..
defects4j checkout -p Math -v 84f -w math_84 && cd math_84 && defects4j compile && cd ..
defects4j checkout -p Math -v 84b -w math_84b && cd math_84b && defects4j compile && cd ..
defects4j checkout -p Lang -v 51f -w lang_51 && cd lang_51 && defects4j compile && cd ..
defects4j checkout -p Lang -v 51b -w lang_51b && cd lang_51b && defects4j compile && cd ..
defects4j checkout -p Math -v 58f -w math_58 && cd math_58 && defects4j compile && cd ..
defects4j checkout -p Math -v 58b -w math_58b && cd math_58b && defects4j compile && cd ..
defects4j checkout -p Time -v 11f -w time_11 && cd time_11 && defects4j compile && cd ..
defects4j checkout -p Time -v 11b -w time_11b && cd time_11b && defects4j compile && cd ..
defects4j checkout -p Chart -v 25f -w chart_25 && cd chart_25 && defects4j compile && cd ..
defects4j checkout -p Chart -v 25b -w chart_25b && cd chart_25b && defects4j compile && cd ..
defects4j checkout -p Math -v 85f -w math_85 && cd math_85 && defects4j compile && cd ..
defects4j checkout -p Math -v 85b -w math_85b && cd math_85b && defects4j compile && cd ..
defects4j checkout -p Chart -v 13f -w chart_13 && cd chart_13 && defects4j compile && cd ..
defects4j checkout -p Chart -v 13b -w chart_13b && cd chart_13b && defects4j compile && cd ..
defects4j checkout -p Math -v 7f -w math_7 && cd math_7 && defects4j compile && cd ..
defects4j checkout -p Math -v 7b -w math_7b && cd math_7b && defects4j compile && cd ..
defects4j checkout -p Math -v 71f -w math_71 && cd math_71 && defects4j compile && cd ..
defects4j checkout -p Math -v 71b -w math_71b && cd math_71b && defects4j compile && cd ..
defects4j checkout -p Time -v 4f -w time_4 && cd time_4 && defects4j compile && cd ..
defects4j checkout -p Time -v 4b -w time_4b && cd time_4b && defects4j compile && cd ..
defects4j checkout -p Math -v 87f -w math_87 && cd math_87 && defects4j compile && cd ..
defects4j checkout -p Math -v 87b -w math_87b && cd math_87b && defects4j compile && cd ..
defects4j checkout -p Lang -v 58f -w lang_58 && cd lang_58 && defects4j compile && cd ..
defects4j checkout -p Lang -v 58b -w lang_58b && cd lang_58b && defects4j compile && cd ..
defects4j checkout -p Math -v 105f -w math_105 && cd math_105 && defects4j compile && cd ..
defects4j checkout -p Math -v 105b -w math_105b && cd math_105b && defects4j compile && cd ..
defects4j checkout -p Lang -v 44f -w lang_44 && cd lang_44 && defects4j compile && cd ..
defects4j checkout -p Lang -v 44b -w lang_44b && cd lang_44b && defects4j compile && cd ..
defects4j checkout -p Lang -v 63f -w lang_63 && cd lang_63 && defects4j compile && cd ..
defects4j checkout -p Lang -v 63b -w lang_63b && cd lang_63b && defects4j compile && cd ..
defects4j checkout -p Chart -v 26f -w chart_26 && cd chart_26 && defects4j compile && cd ..
defects4j checkout -p Chart -v 26b -w chart_26b && cd chart_26b && defects4j compile && cd ..
defects4j checkout -p Math -v 28f -w math_28 && cd math_28 && defects4j compile && cd ..
defects4j checkout -p Math -v 28b -w math_28b && cd math_28b && defects4j compile && cd ..
defects4j checkout -p Math -v 50f -w math_50 && cd math_50 && defects4j compile && cd ..
defects4j checkout -p Math -v 50b -w math_50b && cd math_50b && defects4j compile && cd ..
defects4j checkout -p Math -v 40f -w math_40 && cd math_40 && defects4j compile && cd ..
defects4j checkout -p Math -v 40b -w math_40b && cd math_40b && defects4j compile && cd ..
defects4j checkout -p Math -v 69f -w math_69 && cd math_69 && defects4j compile && cd ..
defects4j checkout -p Math -v 69b -w math_69b && cd math_69b && defects4j compile && cd ..
defects4j checkout -p Math -v 78f -w math_78 && cd math_78 && defects4j compile && cd ..
defects4j checkout -p Math -v 78b -w math_78b && cd math_78b && defects4j compile && cd ..
defects4j checkout -p Math -v 24f -w math_24 && cd math_24 && defects4j compile && cd ..
defects4j checkout -p Math -v 24b -w math_24b && cd math_24b && defects4j compile && cd ..
defects4j checkout -p Chart -v 9f -w chart_9 && cd chart_9 && defects4j compile && cd ..
defects4j checkout -p Chart -v 9b -w chart_9b && cd chart_9b && defects4j compile && cd ..
defects4j checkout -p Math -v 82f -w math_82 && cd math_82 && defects4j compile && cd ..
defects4j checkout -p Math -v 82b -w math_82b && cd math_82b && defects4j compile && cd ..
defects4j checkout -p Chart -v 1f -w chart_1 && cd chart_1 && defects4j compile && cd ..
defects4j checkout -p Chart -v 1b -w chart_1b && cd chart_1b && defects4j compile && cd ..
defects4j checkout -p Time -v 7f -w time_7 && cd time_7 && defects4j compile && cd ..
defects4j checkout -p Time -v 7b -w time_7b && cd time_7b && defects4j compile && cd ..
defects4j checkout -p Math -v 88f -w math_88 && cd math_88 && defects4j compile && cd ..
defects4j checkout -p Math -v 88b -w math_88b && cd math_88b && defects4j compile && cd ..
